### ISSUE TITLE
Horus does not launch in Windows 8 64 Bits 

### ISSUE THREAD

**Issue by mmolero** [bq/horus#17]
Trying to run **horus** on Windows 8.1 64 bits, the next error appears:

```
Traceback (most recent call last):
  File "horus.py", line 43, in <module>
    from horus.gui import app
  File "E:\miguel\workspace\horus\src\horus\gui\app.py", line 35, in <module>
    from horus.gui.main import MainWindow
  File "E:\miguel\workspace\horus\src\horus\gui\main.py", line 42, in <module>
    from horus.gui.workbench.scanning.main import ScanningWorkbench
  File "E:\miguel\workspace\horus\src\horus\gui\workbench\scanning\main.py", line 36, in <module>
    from horus.gui.util.sceneView import SceneView
  File "E:\miguel\workspace\horus\src\horus\gui\util\sceneView.py", line 48, in <module>
    from horus.gui.util import openglHelpers
  File "E:\miguel\workspace\horus\src\horus\gui\util\openglHelpers.py", line 48, in <module>
    glutInit() #Hack; required before glut can be called. Not required for all OS.
  File "C:\Users\Miguel\Anaconda\lib\site-packages\OpenGL\GLUT\special.py", line 323, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
TypeError: 'NoneType' object is not callable
```

----

It can be solved by commenting the following lines (openglHelpers.py):

```python
#if _platform!='darwin':
#	glutInit() #Hack; required before glut can be called. Not required for all OS.
````

Then it works!!!!!

Very nice project, Congrats!!!!

**Comment by Jesus89** [comment]
Thanks for the info!! Probably it is related with OpenGL version. We will study this and will be included in a hotfix. Regards!
